services:
  - type: web
    name: commerece-app
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here
    # - key: MONGODB_URI
    #   sync: false
    # - key: NEXTAUTH_SECRET
    #   sync: false
    # - key: NEXTAUTH_URL
    #   sync: false
    # - key: CLOUDINARY_CLOUD_NAME
    #   sync: false
    # - key: CLOUDINARY_API_KEY
    #   sync: false
    # - key: CLOUDINARY_API_SECRET
    #   sync: false
